// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnmznjztywejubergone.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubXpuanp0eXdlanViZXJnb25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjMyMTIsImV4cCI6MjA2Njc5OTIxMn0.cG5ncbzuevSxquaUGRZ2L7v-yhbOxqzdX9q3C5hXSAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY
    }
  },
  db: {
    schema: 'public'
  }
});

// Debug function para verificar conectividade
export const debugSupabaseConnection = async () => {
  try {
    console.log('🔍 Verificando conectividade do Supabase...');
    console.log('URL:', SUPABASE_URL);
    console.log('Current URL:', window.location.origin);
    
    // Verificar autenticação
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    console.log('👤 Usuário autenticado:', user?.email || 'Não autenticado');
    if (authError) console.error('❌ Erro de autenticação:', authError);
    
    // Teste de conectividade básica
    const { data, error } = await supabase
      .from('project_info')
      .select('id, nome_projeto')
      .limit(1);
      
    if (error) {
      console.error('❌ Erro ao conectar com banco:', error);
      return { success: false, error };
    } else {
      console.log('✅ Conectividade OK. Projetos encontrados:', data?.length || 0);
      return { success: true, data };
    }
  } catch (error) {
    console.error('💥 Erro crítico:', error);
    return { success: false, error };
  }
};